### ISSUE TITLE
fix.satellites is zero

### ISSUE THREAD

**Issue by trogper** [SlashDevin/NeoGPS#105]
I'm using NEO m8n with arduino mkrfox1200. Location works fine, but fix.satellites is zero.
I have verified the NMEA sentences do contain satellite count using http://freenmea.net
Have tried Github version and also from arduino repository.
I have tried sending generated NMEA sentences to arduino via usb-uart, but it didn't work somehow.
I'm not posting the sentences due to security concerns.

**Comment by Sekilsgs2** [comment]
Yes - always zero with neo6m.
Developer whats wrong? where satellites? You have tested example how get number of satellites?

**Comment by trogper** [comment]
Actually it is not an issue of this library. I have not had GST messages enabled, which contain the count. If you use u.blox receiver, try configuring it using u-center.
