### ISSUE TITLE
Usable Example

### ISSUE THREAD

**Issue by samu87** [SlashDevin/NeoGPS#2]
Hi, thanks so much for this code! But if you can i need a simple thing, i wish use your library in my project but i don't understand as i can read the data from the GPS (the example NMEA work and i can read the data) like Serial.print(GPS.lat) can i use the data in this simple way? Can you make me a simple example?! Many thanks!

**Comment by SlashDevin** [comment]
Examples of accessing the various fields (like lat/lon) are shown on the [Data Model](https://github.com/SlashDevin/NeoGPS/blob/master/doc/Data%20Model.md) page.  But it never hurts to have more examples, so I have added [NMEAloc.ino](https://github.com/SlashDevin/NeoGPS/tree/master/examples/NMEAloc) that only handles the RMC sentence, and only prints the lat/lon (if valid).
