### ISSUE TITLE
Problems with example

### ISSUE THREAD

**Issue by Quintenspiering** [SlashDevin/NeoGPS#27]
#include <NeoTeeStream.h> and #include <NeoSWSerial.h> are both not in the download and therefor not working. Where can i find these libs, or can they be uploaded with the rest. This will help me a lot, cause i cant seem to configure my TINY RTK neo m8p through u-blox. Many thanks. 

p.s. forgot to say it was about example rate.

**Comment by SlashDevin** [comment]
Try [this](http://lmgtfy.com/?q=neoteestream) or [this](http://lmgtfy.com/?q=neoswserial).
