### ISSUE TITLE
Using NeoGPS to evaluate Data

### ISSUE THREAD

**Issue by CesMak** [SlashDevin/NeoGPS#4]
Hey,

For analysing purposes, I would like to use NeoGPS on a Windows environment to read in NMEA messages send per serial to my windows laptop. Then I would like to use NeoGPS to write e.g. all the values of only the GPGGA message sentence in different columns of a .txt file.
I will later use this file and copy its values into a exel file and then I hope I will be able to plot these values. 

Is it possible to use NeoGPS just on Windows?

Thanks for your help.

**Comment by SlashDevin** [comment]
Probably.  Most of NeoGPS does not use any Arduino-specific routines, like `Serial.read()` or `millis()`.  However, there are a set of methods that use the Arduino-specific `Stream` type: `available( Stream& )`, `poll` and `send`.  You could just delete those methods.

Basically, if you can read bytes from the PC USB port (serial port?), you can pass them to NeoGPS for parsing.  Obviously, the main program and opening/reading the serial port will be quite different.  But once you have a character, NeoGPS can parse it.  There are two ways to pass characters to NeoGPS.

If you pass characters to `gps.decode`, you would access the `gps.fix()` when DECODE_COMPLETED is returned.  `decode` just manipulates the internal `gps.fix()` member.  NMEAblink.ino is a minimal example of using `decode` and watching for a specific message.  

If you pass characters to `gps.handle`, you would call `gps.available()` (no args) to know when a complete fix has been queued in the fix buffer.  Then call `gps.read()` to dequeue one fix.  NMEA_isr.ino is a minimal example of using 'handle' to process characters.

In either case, you would access a `fix` structure to get the fields you want to write to a file.  You can look at the [Data Model](/SlashDevin/NeoGPS/blob/master/doc/Data%20Model.md) page or [**Streamers.CPP**](https://github.com/SlashDevin/NeoGPS/blob/master/Streamers.cpp) for examples.

To compile on a Windows platform, you would need to do two things, at a minimum:

**1)** If they're not already defined, declare the Windows versions of the 8-bit, 16-bit and 32-bit signed/unsigned integer types that are used on the Arduino: `int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t` and `uint32_t`.  For example,

    #define int8_t unsigned char

or

    typedef unsigned char int8_t;

And similarly for the other types.

**2)** Disable bitfields in structures by commenting out this line in **NeoGPS_cfg.h**:

    //#define NEOGPS_PACKED_DATA

Cheers!
