### ISSUE TITLE
Send GPS data to server http

### ISSUE THREAD

**Issue by AEK-BKF** [SlashDevin/NeoGPS#47]
Hi man,

Thank you so much for your nice packages.
I've arduino sim900 + Neo-6m-0-001 + Arduino Uno.
I can successfully  send GPS data (lat, lng, spd , ...etc ) via sms to a number.
Now I have an http web server, I want to send these data to it,
x.x.x.x/getData.
Please could you give me a code how to setup my url, gprs ?

Thanks.

**Comment by SlashDevin** [comment]
Sorry, I really don't know much about GPRS and pushing data to a web service.
