### ISSUE TITLE
How to get course value ?

### ISSUE THREAD

**Issue by AEK-BKF** [SlashDevin/NeoGPS#48]
Hi,

Please how could I get course and hdop values from fix. ?

**Comment by SlashDevin** [comment]
See the [Data Model page](https://github.com/SlashDevin/NeoGPS/blob/master/extras/doc/Data%20Model.md).  "Course" is called `heading`.

HDOP is in a `fix`, but you have to enable it in GPSfix_cfg.h.  Also make sure that you are parsing a sentence that contains it (see [this table](https://github.com/SlashDevin/NeoGPS/blob/master/extras/doc/Choosing.md)).  You would need to enable GGA or GSA and make sure that your device is sending one of those sentences (use NMEAorder).
