### ISSUE TITLE
add fix.latitude sprintf

### ISSUE THREAD

**Issue by beryindo** [SlashDevin/NeoGPS#51]
how to add fix.latitude sprintf ? I try 
`char tanggalDanJam[100];`
`sprintf(tanggalDanJam,%.6f, (fix.latitude(), 6)`
output is 
`?`

**Comment by SlashDevin** [comment]
Use the utility function [dtostrf](http://www.nongnu.org/avr-libc/user-manual/group__avr__stdlib.html#ga060c998e77fb5fc0d3168b3ce8771d42).

I suggest [searching the Arduino forum for "NeoGPS dtostrf"](https://www.google.com/search?q=neogps+dtostrf&sitesearch=https%3A%2F%2Fforum.arduino.cc)... there are many examples.

For your code, you would do something like

```
char tanggalDanJam[100];
if (fix.valid.location) {
  dtostrf( fix.latitude(), 8, 6, &tanggalDanJam[0] ); // or just tanggalDanJam
  uint8_t pos = strlen( tanggalDanJam ); // check how many chars were written into array
  tanggalDanJam[ pos ] = ','; // a comma after lat (before lon)
  pos++; // increment for comma character
  dtostrf( fix.longitude(), 8, 6, &tanggalDanJam[pos] ); // put lon after comma
}
```
