### ISSUE TITLE
Debug print doesn't appear to support latitudeL

### ISSUE THREAD

**Issue by mjs513** [SlashDevin/NeoGPS#60]
When trying to use Debug_port.print to output lat and long as LatitudeL or LongitudeL the print statement outputs an undecipherable integer.  If I change the print to printf("%li", fix.latitudeL()) it will print it out correctly. 

Thanks
Mike

**Comment by SlashDevin** [comment]
Show me a code snippet.  I hope it was something like

```
  Serial.print( fix.latitudeL() );
```

**Comment by mjs513** [comment]
Didn't try that one.  I used Serial.printf("12li", fix.latitudeL()) on a Teensy.  Would have to use sprint on a Arduino.  Will give Serial.print a try not time I set it up.
