### ISSUE TITLE
ESP32 + NeoGPS + Nextion - usage of all hardware serial 

### ISSUE THREAD

**Issue by sashahn** [SlashDevin/NeoGPS#77]
Hi,
Newbie here and help needed for ESP32  Arduino core.
Done so far:
 - IN HardwareSerial.cpp  for "UART 1" pins definition are changed:
`rxPin = 4;  //was 9`
`txPin = 2;  // was 10`
Reason:  UART 1 uses the same pins as the ESP32 flash memory.

more details on why to do that  can be found on - [hackaday.com](https://hackaday.com/2017/08/17/secret-serial-port-for-arduinoesp32/)

- In IDE Serial ports are declared as below:
`HardwareSerial  DEBUG_PORT(0);      // debug to pc`
`HardwareSerial  GPS_PORT(1);          // GPS Ublox Neo m8n`
`HardwareSerial  DISPLAY_PORT(2);  // Nextion display`

- Does "GPSport.h" has to be edited too?
if so, please advise.

The Library  was tested  with Arduino Mega 2560 and it works like charm, but with ESP32 (Lolin32 board) it has some glitches....Data flow is not consistence, it works but lot of delays appears, not fluid as it was with Mega board.

Thank you and sorry for my bad English

**Comment by SlashDevin** [comment]
> In IDE Serial ports are declared as below:

What do you mean, "In IDE"?  Do you mean:

1.  You modified the core files HardwareSerial.h and .cpp?  I would suggest using the standard names.  In HardwareSerial.h:
```
extern HardwareSerial Serial;
extern HardwareSerial Serial1;
extern HardwareSerial Serial2;
```
... and in HardwareSerial.cpp:

```
HardwareSerial Serial(0);
HardwareSerial Serial1(1);
HardwareSerial Serial2(2);
```
Then use #defines in your sketch to associate a HardwareSerial instance with your specific name:
```
#define DEBUG_PORT   Serial
#define gpsPort      Serial1
#define DISPLAY_PORT Serial2
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**OR** do you mean

2.   They are declared in your sketch (.INO)?  Don't create new HardwareSerial variables in your sketch.  These will be "copies" of variables that were defined in HardwareSerial.cpp.  This can cause unexpected behaviour.

> Does "GPSport.h" has to be edited too?

Only if you are including GPSport.h in your sketch.  If you are declaring your own serial port variables, you do not need this file.  GPSport.h is the one file you would change to make all NeoGPS examples use the same serial port configuration(s).  No other parts of NeoGPS include this file.
