### ISSUE TITLE
Using library with ESP8266

### ISSUE THREAD

**Issue by leobel96** [SlashDevin/NeoGPS#78]
I'm trying to configure the library to work with my NodeMCU board but I don't understand some things: do I need a level shifter for TX and RX pins? How can I configure HardwareSerial port with it? I'm trying to use the "NMEAdiagnostic.ino" sketch but it can't find my board. My connections:
3V3--->VCC
GND--->GND
RX (GPIO 03)--->TX
TX (GPIO 01)--->RX
Thank you!

**Comment by SlashDevin** [comment]
Sorry, I can't help with this hardware question.

**Comment by leobel96** [comment]
@SlashDevin and what about HardwareSerial configuration? Is it enabled by default? If not, how can I configure it with my device?
