### ISSUE TITLE
latitude and longitude DMS is not working

### ISSUE THREAD

**Issue by lukat33** [SlashDevin/NeoGPS#9]
I can get every other specific data from gps_fix except latitude and longitude in DMS.

static gps_fix  fix_data;
Serial.print(fix_data.latitudeDMS.degrees);

gets me compile error:
NMEA:117: error: 'class gps_fix' has no member named 'latitudeDMS'

Thanks for help.

**Comment by SlashDevin** [comment]
It looks like you need to uncomment this in GPSfix_cfg.h:
```
#define GPS_FIX_LOCATION_DMS
```

**Comment by lukat33** [comment]
Oh thank you, I'm sorry if it was obvious.

**Comment by SlashDevin** [comment]
No problem! I've done the same thing many times, so I recognized the error immediately.  :)
